### ISSUE TITLE
error indexing at design matrx, page 192, chapter 11. 

### ISSUE THREAD

**Issue by renc** [thomas-haslwanter/statsintro_python#5]
Thank you very much for this book first, a very good start book for me!  

at chapter 11, page 191, the equation 11.18,
the variable i is from 1 to n, counting for the observed data. 

Error at page 192, "If i = 1 and p = 1 in Eq.11.18, we have a simple linear regression, corresponding to Eq.11.4. If i > 1 we talk about multilinear regression ..."
here, i think it should be "If p = 1 in Eq.11.18, ... simple linear regression, ..... If p > 1 we talk about multilinear regression ..."

The reason is that the n is counting for the data, while p is the indexing for (xi1, xi2, xi3,..., xip). 

Best Regards,
Canjiang

**Comment by thomas-haslwanter** [comment]
Thank you very much for that Feedback!

You are correct, and I have made a note in the "Errata.pdf" on

https://github.com/thomas-haslwanter/statsintro_python


Best regards

th


---
Prof. (FH) PD Dr. Thomas Haslwanter
School of Applied Health and Social Sciences University of Applied Sciences Upper Austria FH OÖ Studienbetriebs GmbH
Garnisonstraße 21
4020 Linz/Austria
Tel.: +43 (0)5 0804 -52170
Fax: +43 (0)5 0804 -52171
E-Mail: Thomas.Haslwanter@fh-linz.at
Web: bim.fh-linz.at
or work.thaslwanter.at

________________________________
