### ISSUE TITLE
Are there solutions On 6.3.1?

### ISSUE THREAD

**Issue by zhangshengshan** [thomas-haslwanter/statsintro_python#7]
As title described , can not find solutions for 6.3.1 Section.

**Comment by thomas-haslwanter** [comment]
I am not sure if I understand the question:
Section 6.3 has the code listed, and in addition a [link to that file](https://github.com/thomas-haslwanter/3D_Kinematics/blob/master/python/C6_gait_analysis.py).

And the Exercises have only 6.1 (simple rotation) & 6.2 (pendulum).

**Comment by thomas-haslwanter** [comment]
I have added a script with the answers, and have them made available on the [ISP github page
](https://github.com/thomas-haslwanter/statsintro_python/blob/master/ISP/Exercise_Solutions/S6_3_1_normalDistribution.py)
